name: Terraform Destroy
on:
  workflow_dispatch:

jobs:
  tf-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'
    steps:
      - uses: actions/checkout@v1

      - name: Install Terraform
        env:
          TERRAFORM_VERSION: "0.12.15"
        run: |
          wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
          unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Terraform init
        run: terraform init -input=false -no-color

      - name: Terraform destroy
        run: terraform destroy -auto-approve -no-color